sudo: required
services:
  - docker

before_install:
  - docker build -t essn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run essn/react-test npm test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t essn/multi-client ./client
  - docker build -t essn/multi-nginx ./nginx
  - docker build -t essn/multi-server ./server
  - docker build -t essn/multi-worker ./worker
  - docker push essn/multi-client
  - docker push essn/multi-nginx
  - docker push essn/multi-server
  - docker push essn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-028822013018
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
